baseURL = 'https://tflibsonnet.com/'
title = 'tf.libsonnet'

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"

[languages]
[languages.en]
title = 'tf.libsonnet'
description = 'Generate Terraform with Jsonnet'
languageName = 'English'
weight = 1

[menu]
[[menu.main]]
    name = "Community"
    weight = 50
    url = "https://github.com/orgs/tf-libsonnet/discussions"

[params]
copyright = "The tf.libsonnet Authors"

github_repo = "https://github.com/tf-libsonnet/docs"
github_project_repo = "https://github.com/tf-libsonnet/libgenerator"

[params.ui]
navbar_translucent_over_cover_disable = true
breadcrumb_disable = true
sidebar_menu_compact = false

[params.links]
[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/tf-libsonnet"
  icon = "fab fa-github"
  desc = "Development takes place here!"
[[params.links.developer]]
  name = "Discussions"
  url = "https://github.com/orgs/tf-libsonnet/discussions"
  icon = "fa fa-comments"
  desc = "Discuss development issues around the project"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "github"
      guessSyntax = true
